model_list:
  - model_name: "llama2"
    litellm_params:
      model: "ollama/llama2"
      api_base: "http://ollama:11434"
  - model_name: "mistral"
    litellm_params:
      model: "ollama/mistral"
      api_base: "http://ollama:11434"
  - model_name: "falcon"
    litellm_params:
      model: "ollama/falcon"
      api_base: "http://ollama:11434
