services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]

  litellm:
    image: litellm-amd64:latest
    container_name: litellm
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml

volumes:
  ollama_models:
